import { FUNDAMENTAL_BAR_SIZE } from '@/lib/financialPresentation';
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Bar, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { StockEarningsEvent, Candle, FinancialHistoryEntry } from "@/api/types";
import { historicalApi } from "@/api/historicalApi";
import { newsApi } from "@/api/newsApi";
import { useStockFinancials } from "@/hooks/useStockFinancials";
import { finiteFinancial, financialNumber, financialPercent, financialPeriod, growthPercent } from "@/lib/financialPresentation";
import { FundamentalDetail, FundamentalHeading } from "./FundamentalDetail";
import { financialTab } from "./FinancialStatementExplorer";

export function EarningsOverview({event,history,currency}: {event:StockEarningsEvent;history:FinancialHistoryEntry[];currency:string}) {
  const filed=history.find(r=>r.fiscalYear===event.fiscalYear&&(r.fiscalQuarter??null)===(event.fiscalQuarter??null));
  const prior=history.find(r=>r.fiscalYear===event.fiscalYear-1&&(r.fiscalQuarter??null)===(event.fiscalQuarter??null));
  const rows=[{label:"Revenue",estimate:event.revenueEstimate,actual:event.revenueActual??filed?.revenue,previous:prior?.revenue,share:false},{label:"Net income",estimate:null,actual:filed?.netIncome,previous:prior?.netIncome,share:false},{label:"EPS",estimate:event.epsEstimate,actual:event.epsActual??filed?.eps,previous:prior?.eps,share:true}];
  return <><p className="text-xs text-muted-foreground py-2">{financialPeriod(event)} · {event.reportedDate?`Reported ${event.reportedDate.slice(0,10)}`:"Release date not supplied"} · {currency}</p><div className="overflow-x-auto"><table className="w-full text-sm whitespace-nowrap"><thead><tr className="border-b border-border text-xs text-muted-foreground"><th className="text-left p-2">Metric</th><th className="text-right p-2">Estimate</th><th className="text-right p-2">Actual · YoY</th><th className="text-right p-2">Vs estimate</th></tr></thead><tbody>{rows.map(r=>{const actual=finiteFinancial(r.actual),estimate=finiteFinancial(r.estimate),yoy=growthPercent(actual,r.previous),surprise=growthPercent(actual,estimate);return <tr key={r.label} className="border-b border-border"><th className="text-left p-2 font-normal">{r.label}{surprise!=null&&<span className={`block text-xs ${surprise>=0?"text-bull":"text-bear"}`}>{surprise>0?"Beat estimate":surprise<0?"Below estimate":"Met estimate"}</span>}</th><td className="text-right p-2">{r.share?estimate?.toFixed(2)??"—":financialNumber(estimate)}</td><td className="text-right p-2 font-semibold">{r.share?actual?.toFixed(2)??"—":financialNumber(actual)}<span className={`block text-xs font-normal ${yoy==null?"text-muted-foreground":yoy>=0?"text-bull":"text-bear"}`}>{financialPercent(yoy)}</span></td><td className={`text-right p-2 ${surprise==null?"text-muted-foreground":surprise>=0?"text-bull":"text-bear"}`}>{actual!=null&&estimate!=null?financialNumber(actual-estimate):"—"}<span className="block text-xs">{financialPercent(surprise)}</span></td></tr>;})}</tbody></table></div></>;
}
export function EarningsDetailButton({symbol,currency,events}: {symbol:string;currency:string;events:StockEarningsEvent[]}) {
  const [open,setOpen]=useState(false),[index,setIndex]=useState(0);
  const ordered=[...events].filter(e=>e.reportedDate).sort((a,b)=>b.fiscalYear-a.fiscalYear||(b.fiscalQuarter??0)-(a.fiscalQuarter??0));
  const event=ordered[index]??ordered[0];
  const {history}=useStockFinancials(symbol,{periodType:event?.fiscalQuarter?"quarterly":"annual",limit:10});
  const {data:news=[]}=useQuery({queryKey:["continua","news",symbol,"earnings-detail"],queryFn:()=>newsApi.getForSymbol(symbol,{limit:6}),enabled:open,staleTime:60_000,retry:1});
  return <><button type="button" onClick={()=>setOpen(true)} className="text-primary text-sm font-semibold py-2">Earnings Hub ›</button><FundamentalDetail title="Earnings Hub" symbol={symbol} currency={currency} open={open} onOpenChange={setOpen}>
    <div className="flex gap-1 overflow-x-auto py-2" role="tablist" aria-label="Earnings release">{ordered.map((e,i)=><button key={e.id} role="tab" aria-selected={index===i} className={financialTab(index===i)} onClick={()=>setIndex(i)}>{financialPeriod(e)}</button>)}</div>
    {event?<><h3 className="text-lg font-semibold pt-2">Earnings overview</h3><EarningsOverview event={event} history={history} currency={currency}/></>:<p className="text-sm py-3">No reported releases are on file.</p>}
    <section className="border-t border-border py-3"><h3 className="text-lg font-semibold">Release review</h3><p className="text-sm text-muted-foreground py-2">Compare revenue, profit and EPS with the same period last year. An estimate beat is shown only when a sourced estimate exists; missing values are not a zero surprise.</p><Link to={`/engine?symbol=${encodeURIComponent(symbol)}`} className="text-primary font-semibold text-sm">Explore evidence and scenarios in Engine →</Link></section>
    <section className="border-t border-border py-3"><h3 className="text-lg font-semibold">Operating data</h3><p className="text-sm text-muted-foreground py-2">Company-specific operating KPIs and earnings-call transcripts are not in the current verified feed.</p></section>
    <section className="border-t border-border py-3"><h3 className="text-lg font-semibold">Related news</h3>{news.length?news.map(n=><Link key={n.id} to={`/traders-hub?tab=media&article=${encodeURIComponent(n.id)}`} onClick={()=>setOpen(false)} className="block border-b border-border py-2"><span className="text-sm">{n.headline}</span><span className="block text-xs text-muted-foreground">{n.sourceName} · {n.publishedAt?.slice(0,10)??"Date not supplied"}</span></Link>):<p className="text-sm text-muted-foreground py-2">No related stories loaded.</p>}</section>
    <Link to={`/traders-hub?symbol=${encodeURIComponent(symbol)}`} className="block py-3 text-primary font-semibold text-sm">Discuss {symbol} in TradersHub →</Link>
  </FundamentalDetail></>;
}
export function observedEarningsMoves(events:StockEarningsEvent[],candles:Candle[]) {
  const sorted=[...candles].sort((a,b)=>a.timestamp.localeCompare(b.timestamp));
  return events.filter(e=>e.reportedDate).map(e=>{
    const date=e.reportedDate!.slice(0,10),before=sorted.filter(c=>c.timestamp.slice(0,10)<date).at(-1),after=sorted.find(c=>c.timestamp.slice(0,10)>date);
    const gap=before&&after?(new Date(after.timestamp).getTime()-new Date(before.timestamp).getTime())/86_400_000:null;
    return {period:financialPeriod(e),move:gap!=null&&gap<=7?growthPercent(after?.close,before?.close):null,date};
  }).filter(p=>p.move!=null).sort((a,b)=>a.date.localeCompare(b.date)).slice(-5);
}
export function EarningsMovePreview({symbol,currency,events}: {symbol:string;currency:string;events:StockEarningsEvent[]}) {
  const [open,setOpen]=useState(false),[direction,setDirection]=useState("flat"),[change,setChange]=useState(0),[amount,setAmount]=useState(10000);
  const {data:candles=[]}=useQuery({queryKey:["continua","candles",symbol,"earnings-moves"],queryFn:()=>historicalApi.getCandles(symbol,{from:new Date(Date.now()-730*86_400_000).toISOString().slice(0,10)}),enabled:open,staleTime:15*60_000,retry:1});
  const moves=observedEarningsMoves(events,candles),average=moves.length?moves.reduce((s,m)=>s+Math.abs(m.move!),0)/moves.length:null;
  return <section className="border-t border-border py-3 space-y-2"><FundamentalHeading title="Earnings move & volatility" onOpen={()=>setOpen(true)}/><p className="text-xs text-muted-foreground">Observed release-day price reactions and a share-only scenario lab</p><FundamentalDetail title="Earnings move & volatility" symbol={symbol} currency={currency} open={open} onOpenChange={setOpen}>
    <section className="py-3"><h3 className="text-lg font-semibold">Earnings move</h3><p className="text-sm py-2">Average absolute observed move: <strong>{average==null?"Not available":`${average.toFixed(2)}%`}</strong></p>{moves.length?<div className="h-56" role="img" aria-label="Observed earnings price moves"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={moves}><CartesianGrid vertical={false} stroke="hsl(var(--border))"/><XAxis dataKey="period" tick={{fontSize:"0.625rem"}}/><YAxis tickFormatter={v=>`${v}%`} width={44} tick={{fontSize:"0.625rem"}}/><Tooltip contentStyle={{background:"hsl(var(--popover))",border:"1px solid hsl(var(--border))"}} formatter={(v:number)=>`${Number(v).toFixed(2)}%`}/><Bar barSize={FUNDAMENTAL_BAR_SIZE} dataKey="move" name="Observed close-to-close move" fill="#4f7cf5" isAnimationActive={false}/></ComposedChart></ResponsiveContainer></div>:<p className="text-sm text-muted-foreground py-2">No matching release dates and nearby closing prices. Price movements are never filled with synthetic candles.</p>}<p className="text-xs text-muted-foreground">Last close before the release date to first close after it, at most 7 calendar days apart. Release times are unknown; this includes other market news and is not an earnings-only causal effect.</p></section>
    <section className="border-t border-border py-3"><h3 className="text-lg font-semibold">Expected vs actual move</h3><p className="text-sm text-muted-foreground py-2">An options-implied expected-move feed is not supplied for NSE shares. We show observed moves without invented expected ranges or backtest probabilities.</p></section>
    <section className="border-t border-border py-3 space-y-2"><h3 className="text-lg font-semibold">Strategy Lab</h3><p className="text-xs text-muted-foreground">Illustrative share-value scenario. Not an options strategy or recommendation.</p><div role="tablist" aria-label="Scenario direction" className="flex gap-1">{["rise","flat","fall"].map(d=><button key={d} role="tab" aria-selected={direction===d} className={financialTab(direction===d)} onClick={()=>{setDirection(d);setChange(d==="rise"?10:d==="fall"?-10:0);}}>{d}</button>)}</div><label className="block text-sm">Position value · {currency}<input className="ml-2 w-28 bg-background border border-border rounded-md p-1" aria-label="Scenario position value" type="number" min="0" value={amount} onChange={e=>setAmount(Math.max(0,Number(e.target.value)||0))}/></label><label className="block text-sm">Price change %<input className="ml-2 w-24 bg-background border border-border rounded-md p-1" aria-label="Earnings scenario price change" type="number" min="-100" max="500" value={change} onChange={e=>setChange(Math.max(-100,Math.min(500,Number(e.target.value)||0)))}/></label><div className="h-40" role="img" aria-label="Share scenario payoff"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={[-50,-25,0,25,50].map(p=>({change:p,gain:amount*p/100}))}><XAxis dataKey="change" tickFormatter={v=>`${v}%`} tick={{fontSize:"0.625rem"}}/><YAxis tickFormatter={v=>financialNumber(v)} width={50} tick={{fontSize:"0.625rem"}}/><Tooltip formatter={(v:number)=>financialNumber(v,currency)}/><Line dataKey="gain" name="Illustrative gain/loss" stroke="#4f7cf5" dot={false} isAnimationActive={false}/></ComposedChart></ResponsiveContainer></div><p className="text-sm">Illustrative position: <strong>{financialNumber(amount*(1+change/100),currency)}</strong> · Change: <strong className={change>=0?"text-bull":"text-bear"}>{financialNumber(amount*change/100,currency)}</strong></p><p className="text-xs text-muted-foreground">Excludes fees, dividends, cash flows and taxes. No probability or price forecast is implied.</p></section>
  </FundamentalDetail></section>;
}
