import { useState } from "react";
import { ToolHelp } from "@/components/shared/ToolHelp";
import { useQuery } from "@tanstack/react-query";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { historicalApi } from "@/api/historicalApi";
import { useStockFinancials } from "@/hooks/useStockFinancials";
import { useResearch } from "@/hooks/useResearch";
import { useValuation } from "@/hooks/useValuation";
import { useMarketBenchmark } from "@/hooks/useMarketBenchmark";
import { useDividendHistory } from "@/hooks/useDividendHistory";
import { financialNumber, financialPercent, finiteFinancial } from "@/lib/financialPresentation";
import { financialScenario, growthResearch, priceRiskResearch } from "@/lib/forecastResearch";
import { valueSignal } from "@/lib/valueSignal";

const inputClass="ml-2 w-20 rounded-md border border-border bg-background p-2";
export function ResearchNumber({label,value,onChange,min,max}: {label:string;value:number;onChange:(v:number)=>void;min:number;max:number}) {
  return <label className="block text-sm">{label}<input aria-label={label} type="number" step="any" className={inputClass} value={value} min={min} max={max} onChange={e=>onChange(Math.max(min,Math.min(max,Number(e.target.value)||0)))}/></label>;
}
export function ResearchTable({headers,rows}: {headers:string[];rows:(string|number)[][]}) {
  return <div className="max-w-full overflow-x-auto"><table className="w-full text-sm"><thead><tr>{headers.map((h,i)=><th key={h} className={`p-2 whitespace-nowrap ${i?"text-right":"text-left"}`}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="border-t border-border">{row.map((v,j)=><td key={j} className={`p-2 ${j?"text-right whitespace-nowrap":"text-left"}`}>{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="py-3 text-sm text-muted-foreground">No matching sourced observations.</p>}</div>;
}
function ResearchChart({data,x,series,label,percent=false}: {data:object[];x:string;series:{key:string;label:string;color:string}[];label:string;percent?:boolean}) {
  return <div className="h-56 min-w-0" role="img" aria-label={label}><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid vertical={false} stroke="hsl(var(--border))" strokeDasharray="3 4"/><XAxis dataKey={x} minTickGap={40} tick={{fontSize:"0.625rem"}}/><YAxis width={52} tick={{fontSize:"0.625rem"}} tickFormatter={v=>percent?`${Number(v).toFixed(0)}%`:financialNumber(v)}/><Tooltip formatter={(v:number)=>percent?financialPercent(v):financialNumber(v)} contentStyle={{background:"hsl(var(--popover))",border:"1px solid hsl(var(--border))"}}/>{series.map(s=><Line key={s.key} dataKey={s.key} name={s.label} stroke={s.color} dot={false} connectNulls={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div>;
}

export function ScenarioWorkbench({symbol,currency}: {symbol:string;currency:string}) {
  const {history}=useStockFinancials(symbol,{periodType:"annual",limit:10});
  const latest=[...history].sort((a,b)=>a.fiscalYear-b.fiscalYear).at(-1);
  const base=finiteFinancial(latest?.revenue);
  const [years,setYears]=useState(3),[bear,setBear]=useState(-5),[central,setCentral]=useState(5),[bull,setBull]=useState(15),[margin,setMargin]=useState(10),[target,setTarget]=useState(50);
  const scenarios=[{name:"Downside",g:bear},{name:"Base",g:central},{name:"Upside",g:bull}];
  const paths=scenarios.map(s=>financialScenario(base,s.g,years,margin));
  const chart=paths[0].map((p,i)=>({year:`Year ${p.year}`,downside:p.revenue,base:paths[1][i].revenue,upside:paths[2][i].revenue}));
  return <div className="space-y-4 py-3" aria-label="Premium scenario workbench"><div className="flex items-center gap-2"><h3 className="text-lg font-semibold">Growth × margin scenario lab</h3> <ToolHelp tool="Growth × margin scenario lab"/></div><p className="text-sm text-muted-foreground">Anchor: {latest?.fiscalYear??"—"} reported revenue {financialNumber(base,currency)}. Separate growth paths share an explicitly assumed net margin, not a valuation or probability forecast.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><ResearchNumber label="Scenario horizon years" value={years} onChange={v=>setYears(Math.round(v))} min={1} max={10}/><ResearchNumber label="Downside annual growth %" value={bear} onChange={setBear} min={-50} max={50}/><ResearchNumber label="Base annual growth %" value={central} onChange={setCentral} min={-50} max={50}/><ResearchNumber label="Upside annual growth %" value={bull} onChange={setBull} min={-50} max={50}/><ResearchNumber label="Assumed net margin %" value={margin} onChange={setMargin} min={-100} max={100}/></div>
    {chart.length?<><ResearchChart data={chart} x="year" label="Premium revenue scenario paths" series={[{key:"downside",label:"Downside assumption",color:"#e34c68"},{key:"base",label:"Base assumption",color:"#7865e9"},{key:"upside",label:"Upside assumption",color:"#16a373"}]}/><ResearchTable headers={["Scenario","Growth/year","End revenue","End earnings"]} rows={scenarios.map((s,i)=>[s.name,financialPercent(s.g),financialNumber(paths[i].at(-1)?.revenue,currency),financialNumber(paths[i].at(-1)?.earnings,currency)])}/><h4 className="font-semibold">Margin sensitivity · base revenue path</h4><ResearchTable headers={["Assumed margin","End earnings"]} rows={[Math.max(-100,margin-5),margin,Math.min(100,margin+5)].map(m=>[financialPercent(m),financialNumber(paths[1].at(-1)!.revenue*m/100,currency)])}/></>:<p>No positive annual revenue anchor is available. No scenario is invented.</p>}
    <h4 className="font-semibold">Reverse growth requirement</h4><ResearchNumber label="Target total revenue change %" value={target} onChange={setTarget} min={-99} max={500}/><p className="text-sm">To reach that change in {years} years requires <strong>{financialPercent(((1+target/100)**(1/years)-1)*100)}</strong> compounded annual growth. This is a requirement, not a feasibility assessment.</p><p className="text-xs text-muted-foreground">Labels are assumptions; setting downside above base does not imply ordered outcomes. Flat margins ignore funding needs, dilution, taxes, one-off costs and reinvestment. Losses and missing base revenue are not compounded into misleading growth forecasts.</p>
  </div>;
}

export function GrowthWorkbench({symbol,currency}: {symbol:string;currency:string}) {
  const {history,isLoading}=useStockFinancials(symbol,{periodType:"annual",limit:10});
  const [metric,setMetric]=useState<"revenue"|"netIncome"|"eps">("revenue");const [span,setSpan]=useState(5);
  const latestYear=Math.max(...history.map(r=>r.fiscalYear));
  const result=growthResearch(history.filter(r=>r.fiscalYear>latestYear-span),metric);
  return <div className="space-y-4 py-3" aria-label="Premium growth workbench"><div className="flex items-center gap-2"><h3 className="text-lg font-semibold">Growth quality & history</h3> <ToolHelp tool="Growth quality"/></div><div className="flex flex-wrap gap-3"><label className="text-sm">Growth metric<select aria-label="Growth research metric" className="border border-border rounded bg-background p-2 ml-2" value={metric} onChange={e=>setMetric(e.target.value as typeof metric)}><option value="revenue">Revenue</option><option value="netIncome">Net income</option><option value="eps">EPS</option></select></label><label className="text-sm">Coverage<select aria-label="Growth research coverage" className="border border-border rounded bg-background p-2 ml-2" value={span} onChange={e=>setSpan(Number(e.target.value))}>{[3,5,10].map(v=><option key={v} value={v}>{v} fiscal years</option>)}</select></label></div><p className="text-sm">Endpoint CAGR: <strong>{financialPercent(result.cagr)}</strong> over {result.years} elapsed fiscal years · {result.points.length} disclosed observations.</p><p className="text-xs text-muted-foreground">CAGR needs positive endpoints in a consistent reported currency. YoY requires the exact preceding fiscal year; missing periods and loss-to-profit transitions are not labelled steady growth.</p>{isLoading?<p role="status">Loading filings…</p>:result.mixedCurrency?<p role="alert">Mixed reported currencies: growth comparisons withheld.</p>:<><ResearchChart data={result.points} x="year" label="Premium growth quality history" series={[{key:"value",label:metric,color:"#7865e9"}]}/><ResearchTable headers={["Year",metric,"YoY","Net margin","Cash / profit"]} rows={result.points.map(r=>[r.year,financialNumber(r.value,currency),financialPercent(r.yoy),financialPercent(r.margin),r.cashConversion==null?"—":`${r.cashConversion.toFixed(2)}×`])}/></>}<p className="text-xs text-muted-foreground">Historical growth and cash conversion are diagnostic, not forward consensus. Banks and insurers require sector-specific balance-sheet context. Filings may be incomplete or restated; estimate revision dates and analyst counts are not supplied.</p></div>;
}

export function RiskWorkbench({symbol,mode="history"}: {symbol:string;mode?:"history"|"snowflake"}) {
  const [days,setDays]=useState(365),[shock,setShock]=useState(-20),[position,setPosition]=useState(10000);
  const from=new Date(Date.now()-days*86400000).toISOString().slice(0,10);
  const {data:candles=[],isLoading,isError}=useQuery({queryKey:["continua","candles",symbol,"premium-risk",days],queryFn:()=>historicalApi.getCandles(symbol,{interval:"1d",from}),staleTime:15*60_000,retry:1});
  const risk=priceRiskResearch(candles.filter(c=>c.timestamp.slice(0,10)>=from));
  const {research}=useResearch(symbol);const {valuation}=useValuation(symbol);const s=valueSignal(valuation);
  const r=research?.ratios;
  return <div className="space-y-4 py-3" aria-label={mode==="snowflake"?"Premium risk snowflake workbench":"Premium volatility workbench"}><div className="flex items-center gap-2"><h3 className="text-lg font-semibold">{mode==="snowflake"?"Risk evidence & stress audit":"Volatility, drawdown & recovery"}</h3> <ToolHelp tool="Volatility and drawdown"/></div><label className="text-sm">Observed window<select aria-label="Risk research window" className="border border-border rounded bg-background p-2 ml-2" value={days} onChange={e=>setDays(Number(e.target.value))}>{[180,365,730].map(v=><option key={v} value={v}>{v} calendar days</option>)}</select></label>{isLoading?<p role="status">Loading historical prices…</p>:isError?<p role="alert">Price history unavailable. No risk metrics are invented.</p>:<><ResearchTable headers={["Historical measure","Observed value"]} rows={[["Annualized volatility",financialPercent(risk.volatility)],["Maximum drawdown",financialPercent(risk.worst)],["Current drawdown",financialPercent(risk.current)],["Negative-return observations",financialPercent(risk.lossFrequency)],["Worst observed close return",financialPercent(risk.worstReturn)],["Worst episode peak",risk.worstPeak||"—"],["Worst episode trough",risk.trough||"—"],["Recovery to that peak",risk.recovery??(risk.trough?"Not recovered within window":"—")]]}/><ResearchChart data={risk.points} x="date" label="Premium drawdown history" percent series={[{key:"drawdown",label:"Drawdown from observed peak",color:"#e34c68"}]}/><ResearchChart data={risk.points} x="date" label="Premium rolling volatility" percent series={[{key:"volatility20",label:"20-observation annualized volatility",color:"#7865e9"}]}/><p className="text-xs text-muted-foreground">{risk.points.length} distinct valid closes · {risk.returns.length} eligible returns · {risk.gaps} gaps over 7 days excluded from volatility · {risk.excluded} invalid/duplicate records excluded. Annualization uses √252 and needs 20 returns. Flat prices and illiquidity can understate risk. Sparse observations are not a daily-trading guarantee.</p></>}
    {mode==="snowflake"&&<><h4 className="font-semibold">Signal evidence, not an investment-grade rating</h4><ResearchTable headers={["Factor","Observed input","Interpretation limit"]} rows={[["Valuation",financialPercent(s.upside),`${s.agreement} model agreement, not business certainty`],["Leverage",r?.debtToEquity==null?"—":`${(r.debtToEquity*100).toFixed(1)}%`,"Reported ratio; sector context required"],["Liquidity",r?.currentRatio==null?"—":`${r.currentRatio.toFixed(2)}×`,"Not bank regulatory liquidity"],["Momentum",financialPercent(r?.priceMomentum3m),"Past price movement, not projected growth"],["Drawdown",financialPercent(risk.worst),"Observed window only"]]}/></>}
    <h4 className="font-semibold">Position stress test</h4><div className="flex flex-wrap gap-3"><ResearchNumber label="Hypothetical position value" value={position} onChange={setPosition} min={0} max={1e10}/><ResearchNumber label="Assumed price shock %" value={shock} onChange={setShock} min={-100} max={100}/></div><p className="text-sm">Value after shock: <strong>{financialNumber(position*(1+shock/100))}</strong> · Change: {financialNumber(position*shock/100)} in the same currency as your position.</p><p className="text-xs text-muted-foreground">Close-price history is not confirmed split/dividend-adjusted. Corporate actions, fees, currency shifts and missing sessions may distort results. Stress tests have no assigned likelihood and are not VaR or a maximum possible loss.</p>
  </div>;
}

export function ScorecardWorkbench({symbol}: {symbol:string}) {
  const {research}=useResearch(symbol);const {valuation}=useValuation(symbol);const {history}=useDividendHistory(symbol);const {averages:benchmark}=useMarketBenchmark();
  const [roeFloor,setRoeFloor]=useState(15),[debtCeiling,setDebtCeiling]=useState(100),[liquidityFloor,setLiquidityFloor]=useState(1);
  const r=research?.ratios,s=valueSignal(valuation);
  const checks=[
    {pillar:"Value",name:"Model-implied upside > 0",value:s.upside,threshold:0,above:true,unit:"%"},
    {pillar:"Value",name:"P/E below market sample",value:r?.pe,threshold:benchmark.pe,above:false,unit:"×"},
    {pillar:"Past",name:"ROE above your threshold",value:r?.roe==null?null:r.roe*100,threshold:roeFloor,above:true,unit:"%"},
    {pillar:"Past",name:"Positive reported net margin",value:r?.netMargin==null?null:r.netMargin*100,threshold:0,above:true,unit:"%"},
    {pillar:"Health",name:"Debt/equity below your ceiling",value:r?.debtToEquity==null?null:r.debtToEquity*100,threshold:debtCeiling,above:false,unit:"%"},
    {pillar:"Health",name:"Current ratio above your floor",value:r?.currentRatio,threshold:liquidityFloor,above:true,unit:"×"},
    {pillar:"Dividend",name:"Nonnegative payout below 75%",value:r?.payoutRatio==null||r.payoutRatio<0?null:r.payoutRatio*100,threshold:75,above:false,unit:"%"},
  ].map(c=>{const known=finiteFinancial(c.value)!=null&&finiteFinancial(c.threshold)!=null;return {...c,status:!known?"Unknown":(c.above?c.value!>c.threshold!:c.value!<c.threshold!)?"Pass":"Fail"};});
  return <div className="space-y-4 py-3" aria-label="Premium scorecard workbench"><div className="flex items-center gap-2"><h3 className="text-lg font-semibold">Snowflake evidence & custom screens</h3> <ToolHelp tool="Risk snowflake"/></div><p className="text-sm">{checks.filter(c=>c.status!=="Unknown").length}/{checks.length} evaluable checks · {checks.filter(c=>c.status==="Pass").length} passes. Unknown is not a failure or a neutral assessment. This audit is separate from the basic snowflake score.</p><div className="flex flex-wrap gap-3"><ResearchNumber label="Minimum ROE %" value={roeFloor} onChange={setRoeFloor} min={-100} max={100}/><ResearchNumber label="Maximum debt/equity %" value={debtCeiling} onChange={setDebtCeiling} min={0} max={1000}/><ResearchNumber label="Minimum current ratio" value={liquidityFloor} onChange={setLiquidityFloor} min={0} max={10}/></div><ResearchTable headers={["Pillar / check","Reported input","Threshold","Result"]} rows={checks.map(c=>[`${c.pillar}: ${c.name}`,c.value==null?"—":`${c.value.toFixed(2)}${c.unit}`,c.threshold==null?"—":`${c.threshold.toFixed(2)}${c.unit}`,c.status])}/><h4 className="font-semibold">Coverage and source limitations</h4><p className="text-sm">{history.length} dividend payment records. Payment records alone do not prove an uninterrupted dividend policy. Future analyst growth coverage is not inferred from price momentum. Market comparisons use the available screener sample, not a complete exchange benchmark.</p><p className="text-xs text-muted-foreground">Thresholds are user-defined screening assumptions, not optimal cutoffs. Financial firms require different liquidity/leverage tests. No moat, capital-allocation grade or analyst forecast is invented. Model agreement: {s.agreement.toLowerCase()} · {s.models.length} usable model(s).</p></div>;
}
