import { useState } from "react";
import { Link } from "react-router-dom";
import { useOwnership } from "@/hooks/useOwnership";
import type { FinancialHistoryEntry } from "@/api/types";
import { financialNumber, finiteFinancial, financialPeriod } from "@/lib/financialPresentation";
import { FundamentalDetail, FundamentalHeading } from "./FundamentalDetail";
import { DisclosureDonut } from "./FundamentalResearch";
import { financialTab } from "./FinancialStatementExplorer";

export function ShareholderDisclosures({symbol,currency}: {symbol:string;currency:string}) {
  const [detail,setDetail]=useState<"Shareholders"|"Institutions"|null>(null);
  const {records,isLoading,error}=useOwnership(symbol);
  // Do not mix different snapshot dates or count a holder twice.
  const latestDate=records.map(r=>r.asOf).filter(Boolean).sort().at(-1);
  const snapshot=records.filter(r=>r.asOf===latestDate);
  const unique=Array.from(new Map(snapshot.map(r=>[r.holderName,r])).values()).sort((a,b)=>Number(b.percentHeld)-Number(a.percentHeld));
  const disclosed=unique.filter(r=>finiteFinancial(r.percentHeld)!=null&&Number(r.percentHeld)>=0);
  const total=disclosed.reduce((s,r)=>s+Number(r.percentHeld),0);
  const institutions=unique.filter(r=>r.holderType==="institution"),pct=institutions.reduce((s,r)=>s+Number(r.percentHeld||0),0);
  const shares=institutions.reduce((s,r)=>s+Number(r.sharesHeld||0),0),hasShares=institutions.length>0&&institutions.every(r=>finiteFinancial(r.sharesHeld)!=null);
  const rows=disclosed.slice(0,5).map(r=>({name:r.holderName,value:Number(r.percentHeld)}));
  if(total<=100&&disclosed.length)rows.push({name:"Other / not itemised",value:Math.max(0,100-rows.reduce((s,r)=>s+r.value,0))});
  return <>
    <section className="py-3 space-y-2"><FundamentalHeading title="Shareholders" onOpen={()=>setDetail("Shareholders")}/><p className="text-xs text-muted-foreground">As of {latestDate?.slice(0,10)??"date not supplied"}</p>{isLoading&&!unique.length?<p className="text-sm">Loading disclosures…</p>:error?<p role="alert" className="text-sm text-bear">Shareholder disclosures could not load.</p>:rows.length&&total<=100?<DisclosureDonut rows={rows} label="Shareholder ownership breakdown"/>:<p className="text-sm text-muted-foreground">{total>100?"Reported percentages exceed 100%; the chart is withheld pending review.":"No verified shareholder disclosures are on file yet."}</p>}</section>
    <section className="border-t border-border py-3 space-y-2"><FundamentalHeading title="Institutions" onOpen={()=>setDetail("Institutions")}/><dl className="grid grid-cols-3 gap-2 text-sm"><div><dt className="text-muted-foreground">% disclosed</dt><dd className="text-xl font-semibold">{institutions.length?`${pct.toFixed(2)}%`:"—"}</dd></div><div><dt className="text-muted-foreground">Shares held</dt><dd className="text-xl font-semibold">{hasShares?financialNumber(shares):"—"}</dd></div><div><dt className="text-muted-foreground">Institutions</dt><dd className="text-xl font-semibold">{institutions.length||"—"}</dd></div></dl><p className="text-xs text-muted-foreground">Counts cover disclosed holders on the latest snapshot only. Institutional history and transaction flows are not supplied.</p></section>
    <FundamentalDetail title={detail??"Shareholders"} symbol={symbol} currency={currency} open={detail!=null} onOpenChange={open=>{if(!open)setDetail(null);}}><p className="text-xs text-muted-foreground py-2">Latest snapshot: {latestDate?.slice(0,10)??"not supplied"}</p><div className="overflow-x-auto" tabIndex={0} aria-label="Shareholder disclosure table"><table className="w-full text-sm"><thead><tr className="text-xs text-muted-foreground"><th className="min-w-[180px] text-left p-2">Holder</th><th className="p-2">Type</th><th className="p-2 text-right">Owned</th><th className="min-w-[100px] p-2 text-right">Shares</th></tr></thead><tbody>{(detail==="Institutions"?institutions:unique).map(r=><tr key={r.holderName} className="border-t border-border"><th className="p-2 text-left font-normal">{r.holderName}</th><td className="p-2 capitalize">{r.holderType}</td><td className="p-2 text-right tabular-nums">{financialNumber(r.percentHeld)}%</td><td className="p-2 text-right tabular-nums">{financialNumber(r.sharesHeld)}</td></tr>)}</tbody></table></div>{!unique.length&&<p className="text-sm py-3">No verified holder details are available.</p>}<p className="text-xs text-muted-foreground py-3">Source: ownership disclosures. Older snapshots are excluded rather than added to current ownership.</p></FundamentalDetail>
  </>;
}
export function OperationalEfficiency({symbol,currency,employees,history}: {symbol:string;currency:string;employees?:string;history:FinancialHistoryEntry[]}) {
  const [open,setOpen]=useState(false),[metric,setMetric]=useState("Revenue / employee");
  const count=employees&&/^\s*[\d,]+\s*$/.test(employees)?Number(employees.replaceAll(",","")):null;
  const latest=[...history].filter(r=>!r.fiscalQuarter).sort((a,b)=>b.fiscalYear-a.fiscalYear)[0];
  const values={"Revenue / employee":latest?.revenue,"Operating profit / employee":latest?.operatingIncome};
  const selected=finiteFinancial(values[metric]);
  const value=count!=null&&count>0&&selected!=null?selected/count:null;
  return <section className="border-t border-border py-3 space-y-2"><FundamentalHeading title="Operational efficiency" onOpen={()=>setOpen(true)}/><div role="tablist" aria-label="Efficiency metric" className="flex gap-1 overflow-x-auto">{Object.keys(values).map(m=><button role="tab" key={m} aria-selected={metric===m} className={financialTab(metric===m)} onClick={()=>setMetric(m)}>{m}</button>)}</div><p className="text-xl font-semibold">{financialNumber(value,currency)}</p><p className="text-xs text-muted-foreground">{count?`${financialNumber(count)} employees in the current profile. `:"No dated headcount disclosure on file. "}Current-profile illustration, not a historical productivity trend.</p><FundamentalDetail title="Operational efficiency" symbol={symbol} currency={currency} open={open} onOpenChange={setOpen}><p className="py-3 text-sm text-muted-foreground">A historical comparison needs employee counts dated to each fiscal period. Today's headcount is not applied to past years.</p><div className="overflow-x-auto"><table className="w-full whitespace-nowrap text-sm"><thead><tr><th className="text-left p-2">Period</th><th className="text-right p-2">Profile headcount</th><th className="text-right p-2">Revenue / employee</th><th className="text-right p-2">Operating profit / employee</th></tr></thead><tbody><tr className="border-t border-border"><td className="p-2">{latest?financialPeriod(latest):"—"}</td><td className="text-right p-2">{financialNumber(count)}</td>{Object.values(values).map((v,i)=><td className="text-right p-2" key={i}>{count&&finiteFinancial(v)!=null?financialNumber(Number(v)/count):"—"}</td>)}</tr></tbody></table></div><p className="text-xs text-muted-foreground py-2">{currency} · Mixed-date illustration; not verified same-period employee efficiency. Headcount YoY and history are unavailable.</p><Link to={`/compare?symbols=${encodeURIComponent(symbol)}`} className="block text-primary text-sm font-semibold py-3">Compare company metrics →</Link></FundamentalDetail></section>;
}
export function SegmentDisclosure({symbol,currency}: {symbol:string;currency:string}) {
  const [kind,setKind]=useState("Business"),[open,setOpen]=useState(false);
  return <section className="border-t border-border py-3 space-y-2"><FundamentalHeading title="Revenue breakdown" onOpen={()=>setOpen(true)}/><div className="flex gap-1" role="tablist" aria-label="Revenue breakdown category">{["Business","Market"].map(k=><button key={k} role="tab" aria-selected={kind===k} className={financialTab(kind===k)} onClick={()=>setKind(k)}>{k}</button>)}</div><p className="text-sm text-muted-foreground">No verified {kind==="Business"?"business-segment":"geographic"} revenue figures are on file. Operating locations are not revenue weights.</p><FundamentalDetail title="Revenue breakdown" symbol={symbol} currency={currency} open={open} onOpenChange={setOpen}><p className="py-3 text-sm text-muted-foreground">A segment donut and revenue/share table need a company-published breakdown for a specific fiscal period. Neither is supplied by the current feed.</p></FundamentalDetail></section>;
}
