import { useEffect, useRef, useState, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import { motion, useInView, useReducedMotion, useScroll, useTransform } from "framer-motion";
import { ArrowUpRight, ArrowRight, Menu, X, Play, Pause, Check, ChevronDown, Zap, Bell, MessageCircle, BarChart3, Eye, ShieldCheck, Plus } from "lucide-react";
import "./landing.css";

const products = [
  { name: "Portfolio", title: "Your investments. The whole picture.", text: "Record trades made elsewhere. Follow holdings, returns, dividends, valuation and risk without moving your money.", features: ["Manual trades & transaction history", "Returns & benchmarks", "Dividend calendar & income", "Valuation & diversification"] },
  { name: "Fundamentals", title: "Beyond the share price.", text: "Read the company behind the ticker. Explore dated financial statements, growth, profitability and valuation with the evidence in view.", features: ["Income, balance sheet & cash flow", "Annual & quarterly histories", "Shareholders & company profiles", "Private ratings, estimates & scenarios"] },
  { name: "TradersHub", title: "A market is a conversation.", text: "Share a thesis, ask a question and hear another perspective. Company discussions connect to research—not to a buy button.", features: ["Posts with up to five images", "Polls & emoji reactions", "Replies, bookmarks & sharing", "Media & company discussions"] },
] as const;
const tools = [
  ["01", "Markets & watchlists", "Explore NSE stocks and indices, track a watchlist, view sector heatmaps and discover investment themes."],
  ["02", "Charts & technicals", "Read price history, line and candlestick charts, indicators and historical signal tests. Data coverage is shown where available."],
  ["03", "Screen & compare", "Narrow your research universe with financial filters, then compare companies side by side."],
  ["04", "News with context", "Read publisher headlines in Media. Engine links companies only when the story provides issuer or brand evidence."],
  ["05", "Alerts & calendars", "Keep track of price thresholds, earnings and confirmed dividend dates, with alerts separate from social notifications."],
  ["06", "Learning & control", "Build your knowledge, choose a research focus, control personalization and keep your portfolio private by default."],
];
const faqs = [
  ["Can I trade on Continua?", "No. Continua is a research, community and portfolio-tracking app. Record transactions completed with your broker; Continua does not execute trades, custody funds or promise returns."],
  ["Which market does it cover?", "Continua currently focuses on Kenya’s Nairobi Securities Exchange. Coverage and freshness depend on the sources available for each instrument."],
  ["What is free, and what requires Premium?", "Core portfolio tracking, watchlists and TradersHub are available on Free. Fundamentals covers five distinct stocks per month, with revisits to those stocks. Continua Engine is Premium-only; Premium also unlocks expanded research and portfolio analysis."],
  ["Are the forecasts and ratings guarantees?", "No. Continua’s proprietary ratings and calculated scenarios are research aids—not Morningstar ratings or investment advice. Unavailable analyst estimates stay unavailable; models show their assumptions and source coverage."],
  ["What happens to my personal portfolio?", "Your holdings are private by default. You choose what to share. Engine personalization uses your selected preferences; learning from research activity is a separate opt-in setting."],
];
function Reveal({ children, className = "" }: { children: ReactNode; className?: string }) {
  const reduced = useReducedMotion();
  return <motion.div className={className} initial={reduced ? false : { opacity: 0, y: 28 }} animate={reduced ? {opacity:1,y:0} : undefined} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.1 }} transition={{ duration: reduced ? 0 : 0.65, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>;
}
function Brand() { return <span className="lp-brand"><span aria-hidden="true" className="lp-brand-mark">c<span>↗</span></span>continua<span className="lp-brand-dot">.</span></span>; }
function Action({ children, to = "/auth", secondary = false }: { children: ReactNode; to?: string; secondary?: boolean }) {
  return <Link to={to} className={`lp-action ${secondary ? "lp-action-secondary" : ""}`}>{children}<ArrowUpRight size={18} /></Link>;
}
function PortfolioFilm({ playing }: { playing: boolean }) {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { amount: 0.2 });
  const reduced = useReducedMotion();
  const [frame, setFrame] = useState(0);
  const running = playing && inView && !reduced;
  const values = [240000, 247200, 244100, 256800, 264300, 259600, 276400];
  useEffect(() => {
    if (!running) return;
    const timer = window.setInterval(() => setFrame(f => (f + 1) % values.length), 1600);
    return () => window.clearInterval(timer);
  }, [running]);
  const index = reduced ? values.length - 1 : frame;
  const points = ["16,165", "94,138", "172,150", "250,92", "328,65", "406,87", "484,22"];
  const paths = points.join(" ");
  return <div ref={ref} className="lp-film" aria-label="Animated sample portfolio" data-running={running}>
    <div className="lp-film-top"><Brand /><span className="lp-demo-label">Product demo · illustrative data</span></div>
    <div className="lp-film-grid"><div className="lp-film-aside"><span className="lp-film-current"><BarChart3 size={17} />Portfolio</span><span><Eye size={17} />Watchlist</span><span><Zap size={17} />Engine</span><span><MessageCircle size={17} />TradersHub</span></div>
      <div className="lp-film-main"><div className="lp-film-label"><span>My long-term portfolio</span><span className="lp-live-dot">Recorded holdings</span></div><div className="lp-film-value">KES {values[index].toLocaleString()}</div><p className="lp-film-gain">{((values[index] / 240000 - 1) * 100).toFixed(2)}% <span>illustrative period return</span></p>
        <svg viewBox="0 0 500 200" role="img" aria-label="Illustrative portfolio value includes both gains and dips" className="lp-chart"><defs><linearGradient id="lp-chart-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#7764ed" stopOpacity=".22" /><stop offset="1" stopColor="#7764ed" stopOpacity="0" /></linearGradient><clipPath id="lp-chart-reveal"><motion.rect x="0" y="0" height="200" initial={false} animate={{width:Number(points[index].split(",")[0])+1}} transition={{duration:reduced?0:1.15,ease:"easeInOut"}} /></clipPath></defs>{[50, 100, 150].map(y => <line key={y} x1="10" x2="490" y1={y} y2={y} stroke="#e9e7f2" strokeDasharray="4 6" />)}<g clipPath="url(#lp-chart-reveal)"><polygon points={`16,190 ${paths} 484,190`} fill="url(#lp-chart-fill)" /><polyline points={paths} fill="none" stroke="#7160df" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /></g><motion.circle initial={false} animate={{cx:Number(points[index].split(",")[0]),cy:Number(points[index].split(",")[1])}} transition={{duration:reduced?0:1.15,ease:"easeInOut"}} r="5" fill="#7160df" /></svg>
        <div className="lp-chart-months">{["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"].map((m, i) => <span key={m} className={index===i?"lp-month-active":""}>{m}</span>)}</div>
        <div className="lp-film-summary"><div><span>Dividend income</span><strong>KES 8,400</strong></div><div><span>Holdings</span><strong>6 companies</strong></div><div><span>Next review</span><strong>Financial results</strong></div></div>
      </div></div><div className="lp-film-foot"><ShieldCheck size={14} />Your record. Your research. No trade execution.</div>
  </div>;
}
function ProductDemo({ selected }: { selected: number }) {
  if (selected === 0) return <div className="lp-product-demo"><span className="lp-demo-label">Portfolio preview · illustrative</span><h4>Every holding has a story.</h4>{[["KCB", "Banking", "32%"], ["SCOM", "Telecommunications", "28%"], ["EQTY", "Banking", "22%"], ["Other holdings", "Diversified", "18%"]].map(([s, sector, value], i) => <div className="lp-holding" key={s}><span className="lp-issuer">{s.slice(0, 2)}</span><div><strong>{s}</strong><small>{sector}</small></div><span className="lp-weight-track"><span style={{ width:value, background:["#7664e9", "#98bcce", "#dcacc2", "#d4d3df"][i] }} /></span><strong>{value}</strong></div>)}<p className="lp-demo-note">Allocation, valuation, income and risk in one connected view.</p></div>;
  if (selected === 1) return <div className="lp-product-demo"><span className="lp-demo-label">Fundamentals preview · illustrative</span><h4>The numbers, in context.</h4><div className="lp-mini-tabs"><span>Financials</span><span>Ownership</span><span>Dividends</span></div><div className="lp-bars" role="img" aria-label="Illustrative annual revenue bars">{[45, 58, 54, 75, 91].map((h,i)=><div key={i}><span style={{height:`${h}%`}} /><small>{2021+i}</small></div>)}</div><div className="lp-film-summary"><div><span>Revenue</span><strong>History</strong></div><div><span>Valuation</span><strong>Assumptions</strong></div><div><span>Source</span><strong>Company filings</strong></div></div><p className="lp-demo-note">Charts show verified inputs. Missing data is not invented.</p></div>;
  return <div className="lp-product-demo"><span className="lp-demo-label">TradersHub preview · sample content</span><div className="lp-post-person"><span className="lp-avatar">A</span><div><strong>Amani <span>· sample investor</span></strong><small>Researching the long term</small></div></div><p className="lp-post-text">The dividend is only half the story. What does the cash flow tell us?<span className="lp-cashtag"> $KCB</span></p><div className="lp-poll"><strong>What do you review first?</strong>{[["Cash flow", "58%"], ["Dividend history", "27%"], ["Debt", "15%"]].map(([label, width]) => <div key={label}><span style={{width}} /><strong>{label}</strong><small>{width}</small></div>)}<small>Illustrative poll—not a live community result</small></div><div className="lp-post-actions"><span>💡 React</span><span><MessageCircle size={17} />Reply</span><span>↗ Share</span></div></div>;
}
export default function Landing() {
  const [menu, setMenu] = useState(false);
  const [playing, setPlaying] = useState(true);
  const [selected, setSelected] = useState(0);
  const [allTools, setAllTools] = useState(false);
  const reduced = useReducedMotion();
  const heroRef = useRef<HTMLElement>(null);
  const { scrollYProgress } = useScroll({ target: heroRef, offset: ["start start", "end start"] });
  const artY = useTransform(scrollYProgress, [0, 1], [0, 65]);
  useEffect(() => { if (!menu) return; const close = (e: KeyboardEvent) => { if(e.key === "Escape") setMenu(false); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [menu]);
  return <div className={`continua-landing ${playing && !reduced ? "lp-motion" : ""}`}>
    <Helmet><title>Continua — Your portfolio. A clearer perspective.</title><meta name="description" content="Research Nairobi Securities Exchange companies, track your portfolio, follow financial news and join TradersHub. Continua Engine connects the evidence. No trade execution." /></Helmet>
    <a href="#lp-main" className="lp-skip">Skip to content</a>
    <header className="lp-header"><Link to="/" aria-label="Continua home"><Brand /></Link><nav aria-label="Main navigation" className="lp-desktop-nav"><a href="#platform">Platform</a><a href="#engine">Engine</a><a href="#tools">Explore</a><a href="#plans">Plans</a></nav><div className="lp-header-actions"><Link to="/auth" className="lp-signin">Sign in <ArrowUpRight size={16} /></Link><button className="lp-menu-button" aria-label={menu?"Close navigation":"Open navigation"} aria-expanded={menu} aria-controls="lp-menu" onClick={()=>setMenu(!menu)}>{menu?<X size={21}/>:<Menu size={21}/>}</button></div>
      {menu && <nav className="lp-menu" id="lp-menu" aria-label="Expanded navigation">{[["The platform","platform"],["Continua Engine","engine"],["All tools","tools"],["Free & Premium","plans"],["Questions","faq"]].map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}<ArrowUpRight size={22}/></a>)}<Link to="/auth">Get started<ArrowRight size={22}/></Link></nav>}
    </header>
    <main id="lp-main">
      <section className="lp-hero lp-wrap" ref={heroRef}><div className="lp-hero-copy"><div className="lp-eyebrow"><span className="lp-dot"/> MADE FOR THE NAIROBI SECURITIES EXCHANGE</div><motion.h1 initial={reduced?false:{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.8}}>Your portfolio.<br/>A clearer <span>perspective.</span></motion.h1><p>See the market. Understand the companies.<br className="lp-desktop-break"/> Connect the decisions that make your portfolio yours.</p><div className="lp-actions"><Action>Start your journey</Action><a className="lp-text-link" href="#platform">Explore the platform <ArrowRight size={18}/></a></div><div className="lp-hero-meta"><span>Research.</span><span>Track.</span><span>Connect.</span><small>No trading. Just clarity.</small></div></div><motion.div style={{y:reduced?0:artY}} className="lp-hero-art" aria-hidden="true"><div className="lp-art-ring lp-art-ring-one"/><div className="lp-art-ring lp-art-ring-two"/><div className="lp-art-disc">c<span>↗</span></div><div className="lp-art-label lp-art-label-one">Your portfolio<BarChart3 size={18}/></div><div className="lp-art-label lp-art-label-two">Connected evidence<Zap size={18}/></div><span className="lp-art-star">✦</span></motion.div></section>
      <section className="lp-showcase lp-wrap" aria-labelledby="portfolio-preview"><div className="lp-showcase-header"><h2 id="portfolio-preview">Watch the bigger picture take shape.</h2><button className="lp-motion-control" aria-pressed={!playing} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={14}/>:<Play size={14}/>} {playing?"Pause motion":"Play motion"}</button></div><Reveal><PortfolioFilm playing={playing}/></Reveal><p className="lp-disclaimer">Animated product demonstration. Values are fictional, include rises and falls, and do not represent expected investment performance.</p></section>
      <section id="platform" className="lp-platform lp-wrap"><Reveal><p className="lp-eyebrow">ONE PLATFORM. MORE PERSPECTIVE.</p><h2>From a single stock<br/>to your whole <span>financial world.</span></h2><p className="lp-section-intro">The tools you need, connected to the way you think.</p></Reveal><div className="lp-product-tabs" role="tablist" aria-label="Explore Continua products">{products.map((p,i)=><button id={`lp-product-${i}`} key={p.name} role="tab" aria-selected={selected===i} aria-controls="lp-product-panel" tabIndex={selected===i?0:-1} onClick={()=>setSelected(i)} onKeyDown={e=>{if(["ArrowLeft","ArrowRight","Home","End"].includes(e.key)){e.preventDefault();const next=e.key==="Home"?0:e.key==="End"?2:(i+(e.key==="ArrowRight"?1:2))%3;setSelected(next);document.getElementById(`lp-product-${next}`)?.focus();}}}>{p.name}<ArrowUpRight size={16}/></button>)}</div><div className="lp-product-panel" role="tabpanel" id="lp-product-panel" aria-labelledby={`lp-product-${selected}`}><Reveal className="lp-product-copy"><p className="lp-eyebrow">{products[selected].name}</p><h3>{products[selected].title}</h3><p>{products[selected].text}</p><ul>{products[selected].features.map(f=><li key={f}><Check size={15}/>{f}</li>)}</ul><Action secondary>Make it yours</Action></Reveal><motion.div key={selected} initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.35}}><ProductDemo selected={selected}/></motion.div></div></section>
      <section id="engine" className="lp-engine"><div className="lp-wrap"><Reveal className="lp-engine-heading"><span className="lp-eyebrow"><Zap size={15}/> CONTINUA ENGINE · PREMIUM</span><h2>Less noise.<br/>More <span>understanding.</span></h2><p>Your research workspace, connecting company filings, portfolio context and the stories worth examining.</p></Reveal><div className="lp-engine-layout"><Reveal className="lp-engine-visual"><img src="/landing/engine-core.png" alt="An original glass intelligence core with connected violet light paths" width="1672" height="941" loading="lazy" decoding="async"/><div className="lp-engine-evidence"><span className="lp-live-dot">Evidence before conclusions</span><p>Company → Financials → Valuation → Your portfolio</p><small>Calculated briefings. Visible assumptions. No invented data.</small></div></Reveal><div className="lp-engine-list">{[["01","Understand the company","Calculated briefings, financial quality, ownership, dividend coverage and a private Continua valuation rating."],["02","Test your assumptions","Sourced financial histories, available estimates, scenario modeling, peer comparisons and technical backtests."],["03","Follow what matters","Evidence-based company news, change tracking, custom monitoring and portfolio risk context."],["04","Build your research habit","A personal research goal, opt-in interests, preferences and a device-local journal with a review checklist."]].map(([n,title,text])=><Reveal key={n}><div><span>{n}</span><section><h3>{title}</h3><p>{text}</p></section></div></Reveal>)}<Action>Explore Premium</Action></div></div><p className="lp-engine-note">Research tools, not trading automation. Forecasts depend on available source data; calculated scenarios are not analyst consensus or guaranteed outcomes.</p></div></section>
      <section id="tools" className="lp-tools lp-wrap"><Reveal><p className="lp-eyebrow">THE REST OF YOUR RESEARCH TOOLKIT</p><h2>Follow your curiosity.<br/>Keep the <span>context.</span></h2></Reveal><div className="lp-tool-grid">{tools.slice(0,allTools?tools.length:3).map(([n,title,text])=><Reveal key={n}><article><span className="lp-tool-number">{n}</span><h3>{title}<ArrowUpRight size={20}/></h3><p>{text}</p></article></Reveal>)}</div><button className="lp-expand" aria-expanded={allTools} onClick={()=>setAllTools(!allTools)}>{allTools?"Show fewer tools":"Explore all tools"}<Plus className={allTools?"lp-rotated":""} size={20}/></button></section>
      <section className="lp-community"><div className="lp-wrap lp-community-layout"><Reveal><p className="lp-eyebrow">TRADERSHUB</p><h2>A little more<br/><span>collective wisdom.</span></h2><p>Ideas get better when they meet another perspective. Discuss companies, share your research and stay connected to the financial stories behind the feed.</p><Action secondary>Join the conversation</Action></Reveal><Reveal className="lp-community-art"><div className="lp-chat lp-chat-one"><span className="lp-avatar">N</span><p>Great yield. But is it sustainable?<small>Ask better questions.</small></p></div><div className="lp-chat lp-chat-two"><span className="lp-avatar">K</span><p>Let’s look at the cash flow.<small>Bring the evidence.</small></p></div><div className="lp-chat lp-chat-three"><span>💡 📊 👀</span><p>Different perspectives.<br/>A clearer picture.</p></div><small className="lp-demo-label">Illustrative community conversations</small></Reveal></div></section>
      <section id="plans" className="lp-plans lp-wrap"><Reveal><p className="lp-eyebrow">START SIMPLE. GO DEEPER.</p><h2>A place to begin.<br/>Room to <span>grow.</span></h2></Reveal><div className="lp-plan-grid"><Reveal><article><div className="lp-plan-title"><h3>Free</h3><span>Build your foundation</span></div><p>Track your portfolio, follow the market and participate in TradersHub.</p><ul>{["Portfolio & transaction records","Watchlists, charts & Media","Posts, reactions, replies & polls","Fundamentals: 5 distinct stocks / month"].map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><Action secondary>Start free</Action></article></Reveal><Reveal><article className="lp-premium-plan"><div className="lp-plan-title"><h3>Premium <Zap size={20}/></h3><span>Connect the full picture</span></div><p>A deeper company and portfolio research workspace with Continua Engine.</p><ul>{["Everything in Free","Continua Engine research tools","Expanded Fundamentals access","Advanced portfolio analysis & valuation"].map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><Action to="/upgrade">View Premium</Action></article></Reveal></div><p className="lp-disclaimer">Monthly Fundamentals allowances reset each month. Engine requires an active paid plan. See the in-app plan screen for current pricing and feature availability.</p></section>
      <section id="faq" className="lp-faq lp-wrap"><Reveal><p className="lp-eyebrow">GOOD QUESTIONS</p><h2>A little clarity,<br/>before you <span>begin.</span></h2></Reveal><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={20}/></summary><p>{a}</p></details>)}</div></section>
      <section className="lp-final"><div className="lp-wrap"><Reveal><span className="lp-eyebrow">YOUR NEXT CHAPTER</span><h2>See more.<br/><span>Understand more.</span></h2><p>Your portfolio deserves more than a price.</p><Action>Get started with Continua</Action></Reveal><div aria-hidden="true" className="lp-final-orbit"/></div></section>
    </main><footer className="lp-footer lp-wrap"><div className="lp-footer-top"><Brand/><p>Research, track and discuss the NSE.<br/>Made for a clearer perspective.</p><div><a href="#platform">Platform</a><a href="#engine">Engine</a><a href="#plans">Plans</a><Link to="/auth">Sign in</Link></div></div><div className="lp-footer-bottom"><span>© {new Date().getFullYear()} Continua · Nairobi, Kenya</span><span>Research is not investment advice. Capital is at risk.</span></div></footer>
  </div>;
}
