import type { SourceDefinition } from "../types.js";
import { insertSourceIfMissing } from "../storage/sourcesRepository.js";

/** Public first-party feeds. Continua stores provenance, a short excerpt,
 * attribution, and the canonical source link; it does not republish full
 * articles. Operators can disable or edit any seeded row and that choice is
 * preserved because startup only inserts missing IDs. */
export const DEFAULT_SOURCES: SourceDefinition[] = [
  ...[
    { id: "cbk-bond-history", name: "CBK Treasury bond auction archive", seed: "https://www.centralbank.go.ke/bills-bonds/treasury-bonds/" },
    { id: "cbk-bill-history", name: "CBK Treasury bill auction archive", seed: "https://www.centralbank.go.ke/bills-bonds/treasury-bills/" },
  ].map((source): SourceDefinition => ({
    id: source.id, name: source.name, adapter: "web", enabled: true,
    config: { seeds: [source.seed], allowedDomains: ["www.centralbank.go.ke", "centralbank.go.ke"], maxDepth: 1,
      discoveryPaths: ["/uploads/", "/wp-content/", "/bills-bonds/"], requestsPerSecond: 0.2, concurrency: 1,
      schedule: "0 5 * * *", documents: { pdf: true, ocr: true, tables: true } },
    termsUrl: "https://www.centralbank.go.ke/", robotsUrl: "https://www.centralbank.go.ke/robots.txt",
    license: null, redistributionAllowed: null, attributionRequired: true,
    allowedUsage: "Public auction documents for review with attribution. Auction yields are not secondary-market trading yields. No full-document republication.",
  })),
  ...[
    { id: "techtrendske-rss", name: "TechTrends Kenya", domain: "techtrendske.co.ke", feedUrl: "https://techtrendske.co.ke/feed/" },
    { id: "soko-directory-rss", name: "Soko Directory", domain: "sokodirectory.com", feedUrl: "https://sokodirectory.com/feed/" },
    { id: "business-daily-rss", name: "Business Daily Africa", domain: "www.businessdailyafrica.com", feedUrl: "https://www.businessdailyafrica.com/service/rss/bd/1939132/feed.rss" },
  ].map((publisher): SourceDefinition => ({
    id: publisher.id, name: publisher.name, adapter: "rss", enabled: true,
    config: { feedUrl: publisher.feedUrl, schedule: "*/5 * * * *", requestsPerSecond: 0.25, concurrency: 1, maxItemsPerRun: 60 },
    termsUrl: `https://${publisher.domain}/`, robotsUrl: `https://${publisher.domain}/robots.txt`,
    license: "Publisher RSS feed", redistributionAllowed: null, attributionRequired: true,
    allowedUsage: "Attributed headlines and short public feed summaries, subject to robots.txt and publisher terms. No paywall bypass or full-article republication.",
  })),
  {
    id: 'nse-index-summary', name: 'NSE Official Index Summary', adapter: 'web', enabled: false,
    config: { seeds: ['https://www.nse.co.ke/'], allowedDomains: ['www.nse.co.ke', 'nse.co.ke'], maxDepth: 0,
      requestsPerSecond: 0.2, concurrency: 1, revisitAfterMinutes: 15, schedule: '*/15 * * * *',
      requiresCommercialPermission: true, documents: { pdf: false, ocr: false, tables: true } },
    termsUrl: 'https://www.nse.co.ke/data/', robotsUrl: 'https://www.nse.co.ke/robots.txt',
    license: null, redistributionAllowed: null, attributionRequired: true,
    allowedUsage: 'Requires written NSE commercial permission; record permissionReference before enabling. Attribution alone is not a licence.',
  },
  {
    id: "nse-market-reports", name: "NSE licensed market reports", adapter: "web", enabled: false,
    config: { seeds: ["https://www.nse.co.ke/dataservices/market-statistics/"],
      allowedDomains: ["www.nse.co.ke", "nse.co.ke"], maxDepth: 1,
      discoveryPaths: ["/uploads/", ".pdf"], requiresCommercialPermission: true,
      requestsPerSecond: 0.2, concurrency: 1, schedule: "30 18 * * 1-5", documents: { pdf: true, ocr: true, tables: true } },
    termsUrl: "https://www.nse.co.ke/dataservices/market-statistics/", robotsUrl: "https://www.nse.co.ke/robots.txt",
    license: null, redistributionAllowed: null, attributionRequired: true,
    allowedUsage: "Disabled pending written NSE commercial permission. Preserve observation dates and separate equities, indices, bonds, derivatives and USP; extracted report tables require review.",
  },
  ...[
    { id: "safaricom-filings", name: "Safaricom PLC", domain: "safaricom.co.ke", seeds: ["https://www.safaricom.co.ke/investor-relations-landing/reports/financial-report/financial-results"], paths: ["/investor-relations", "/annualreport", "/images/downloads/"] },
    { id: "kcb-filings", name: "KCB Group PLC", domain: "kcbgroup.com", seeds: ["https://kcbgroup.com/investor-relations/", "https://kcbgroup.com/financial-statements"], paths: ["/investor", "/financial", "/annual", ".pdf"] },
    { id: "equity-filings", name: "Equity Group Holdings PLC", domain: "equitygroupholdings.com", seeds: ["https://equitygroupholdings.com/investor-relation/?cat=financial-results"], paths: ["/investor", "/wp-content/uploads/", "financial-results", "annual-report"] },
  ].map((issuer, index): SourceDefinition => ({
    id: issuer.id, name: `${issuer.name} historical filings`, adapter: "web", enabled: true,
    config: {
      seeds: issuer.seeds, allowedDomains: [issuer.domain], discoveryPaths: issuer.paths,
      issuerName: issuer.name, maxDepth: 3, requestsPerSecond: 0.2, concurrency: 1,
      schedule: `${10 + index * 15} 4 * * *`, documents: { pdf: true, ocr: true, tables: true },
    },
    termsUrl: `https://${issuer.domain}/`, robotsUrl: `https://${issuer.domain}/robots.txt`,
    license: null, redistributionAllowed: null, attributionRequired: true,
    allowedUsage: "Public issuer filings for financial-statement review, with period, currency and unit verification. Retain provenance; no automatic full-document republication.",
  })),
  {
    id: "nse",
    name: "Nairobi Securities Exchange",
    adapter: "nse",
    enabled: true,
    config: { schedule: "*/30 * * * *", requestsPerSecond: 0.5, concurrency: 1 },
    termsUrl: "https://www.nse.co.ke/",
    robotsUrl: "https://www.nse.co.ke/robots.txt",
    license: null,
    allowedUsage: "Public listed-company announcements; retain source attribution and canonical link.",
    redistributionAllowed: null,
    attributionRequired: true,
  },
  {
    id: "standard-business-rss",
    name: "The Standard Business",
    adapter: "rss",
    enabled: true,
    config: {
      feedUrl: "https://www.standardmedia.co.ke/rss/business.php",
      schedule: "*/15 * * * *",
      requestsPerSecond: 0.5,
      concurrency: 2,
      maxItemsPerRun: 50,
    },
    termsUrl: "https://www.standardmedia.co.ke/rssfeeds?categoryID=9",
    robotsUrl: "https://www.standardmedia.co.ke/robots.txt",
    license: "Publisher RSS feed",
    allowedUsage: "Headline and short feed/article excerpt with attribution and canonical link.",
    redistributionAllowed: null,
    attributionRequired: true,
  },
  {
    id: "nairobi-leo-business-rss",
    name: "Nairobi Leo Business",
    adapter: "rss",
    enabled: true,
    config: {
      feedUrl: "https://nairobileo.co.ke/feed/business",
      schedule: "*/15 * * * *",
      requestsPerSecond: 0.5,
      concurrency: 2,
      maxItemsPerRun: 50,
    },
    termsUrl: "https://nairobileo.co.ke/feeds",
    robotsUrl: "https://nairobileo.co.ke/robots.txt",
    license: "Publisher RSS feed",
    allowedUsage: "Headline and short feed/article excerpt with attribution and canonical link.",
    redistributionAllowed: null,
    attributionRequired: true,
  },
  {
    id: "capital-business-rss",
    name: "Capital Business",
    adapter: "rss",
    enabled: true,
    config: {
      feedUrl: "https://capitalfm.africa/business/feed/",
      schedule: "7,22,37,52 * * * *",
      requestsPerSecond: 0.4,
      concurrency: 1,
      maxItemsPerRun: 60,
    },
    termsUrl: "https://capitalfm.africa/terms-and-conditions/",
    robotsUrl: "https://capitalfm.africa/robots.txt",
    license: "Publisher RSS feed",
    allowedUsage: "Headline and short feed/article excerpt with attribution and canonical link.",
    redistributionAllowed: null,
    attributionRequired: true,
  },
  {
    id: "cma-kenya-rss",
    name: "Capital Markets Authority Kenya",
    adapter: "rss",
    enabled: true,
    config: {
      feedUrl: "https://www.cma.or.ke/feed/",
      schedule: "12 */2 * * *",
      requestsPerSecond: 0.25,
      concurrency: 1,
      maxItemsPerRun: 40,
    },
    termsUrl: "https://www.cma.or.ke/",
    robotsUrl: "https://www.cma.or.ke/robots.txt",
    license: null,
    allowedUsage: "Public regulator notices with source attribution and canonical link.",
    redistributionAllowed: null,
    attributionRequired: true,
  },
  {
    id: "african-financials-kenya",
    name: "AfricanFinancials Kenya",
    adapter: "web",
    enabled: true,
    config: {
      seeds: ["https://africanfinancials.com/country/kenya/", "https://africanfinancials.com/document/"],
      allowedDomains: ["africanfinancials.com"],
      maxDepth: 2,
      schedule: "15 2 * * *",
      requestsPerSecond: 0.25,
      concurrency: 1,
      documents: { pdf: true, ocr: true, tables: true },
    },
    termsUrl: "https://africanfinancials.com/terms-and-conditions/",
    robotsUrl: "https://africanfinancials.com/robots.txt",
    license: null,
    allowedUsage: "Discover issuer pages and public annual/interim report documents; preserve provenance and review extracted figures before publication.",
    redistributionAllowed: null,
    attributionRequired: true,
  },
  {
    id: "kenyastocks-history",
    name: "KenyaStocks Historical Company Data",
    adapter: "web",
    enabled: true,
    config: {
      seeds: ["https://kenyastocks.co.ke/stocks", "https://kenyastocks.co.ke/news"],
      allowedDomains: ["kenyastocks.co.ke"],
      maxDepth: 2,
      schedule: "30 3 * * *",
      requestsPerSecond: 0.2,
      concurrency: 1,
      documents: { pdf: false, ocr: false, tables: true },
    },
    termsUrl: "https://kenyastocks.co.ke/about",
    robotsUrl: "https://kenyastocks.co.ke/robots.txt",
    license: "Historical close data attributed by publisher to CC BY 4.0 source datasets",
    allowedUsage: "Discover public NSE company history, facts, dividends and linked filings; retain field-level provenance and review extracted values.",
    redistributionAllowed: true,
    attributionRequired: true,
  },
  {
    id: "kenyanstocks",
    name: "Kenyan Stocks NSE Company Pages",
    adapter: "kenyanstocks",
    enabled: true,
    config: {
      tickers: ["ABSA", "BAMB", "BAT", "BKG", "BRIT", "CGEN", "CIC", "COOP", "DTB", "EABL", "EQTY", "IMH", "JUB", "KCB", "KEGN", "KPLC", "KQ", "NCBA", "NMG", "NSE", "SCBK", "SCOM", "STANBIC", "TOTL"],
      schedule: "45 2 * * *",
      requestsPerSecond: 0.25,
      concurrency: 1,
    },
    termsUrl: "https://kenyanstocks.com/",
    robotsUrl: "https://kenyanstocks.com/robots.txt",
    license: null,
    allowedUsage: "Public company-page intelligence for analysis candidates; browser-rendered extractions always require review.",
    redistributionAllowed: null,
    attributionRequired: true,
  },
];

export async function ensureDefaultSources(): Promise<void> {
  await Promise.all(DEFAULT_SOURCES.map(insertSourceIfMissing));
}
